# Generated by Django 5.0.6 on 2025-06-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.AlterModelOptions(
            name='biblioteca',
            options={'managed': True, 'verbose_name': 'Biblioteca', 'verbose_name_plural': 'Bibliotecas'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': True, 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'managed': True, 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='detallecontenido',
            options={'managed': True, 'verbose_name': 'Detalle de Contenido', 'verbose_name_plural': 'Detalles de Contenido'},
        ),
        migrations.AlterModelOptions(
            name='detallecurso',
            options={'managed': True, 'verbose_name': 'Detalle de Curso', 'verbose_name_plural': 'Detalles de Curso'},
        ),
        migrations.AlterModelOptions(
            name='foro',
            options={'managed': True, 'verbose_name': 'Foro', 'verbose_name_plural': 'Foros'},
        ),
        migrations.AlterModelOptions(
            name='modulos',
            options={'managed': True, 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'managed': True, 'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True, 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
